title: Mazaharul Abedin
author: Mazaharul Abedin
email: mazaharul.rs@presiuniv.ac.in
# description: >-
#   Academic portfolio of Mazaharul Abedin. PhD Research Scholar at Presidency University, Kolkata. 
#   Exploring Observational Cosmology, Dark Energy, and Machine Learning applications in Physics.

# --- Technical Settings ---
baseurl: "" 
url: "https://maza75.github.io" 

# --- Theme & Visuals ---
theme: minima
header_pages:
  - index.md
  - publications.md
  - gallery.md

# --- Social Media (Appears in Footer) ---
github_username: maza75

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
